### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by mkostin** [steenhulthin/reStructuredText_NPP#1]
thanks for the plugin! Can't install though, can't find "User Defined" option in referenced menu item (View). Latest n++ is installed. Any directions?

**Comment by steenhulthin** [comment]
Thanks for the issue and sorry for my (very) late answer. (I've been away from the community part of software development for some time - hoping to return again now though).
You are right: there is no longer a `User Defined`option under view, however under `Language` -> `Define your language...` you can get access to the `import` button. 
I'll keep this issue open until I have fixed the installation instructions.

**Comment by steenhulthin** [comment]
This is issue should now be fixed with commit ad0228793ea69969ef85ead6a3d03ea4521d76b5
