### ISSUE TITLE
Non-white backgrounds

### ISSUE THREAD

**Issue by flaudanum** [steenhulthin/reStructuredText_NPP#3]
Hello,
It seems that the syntax highlight requires a white background. When I use a dark theme, non-blank characters have a white background which makes a weird visual. So I had to switch to the default white background.
Thanks

**Comment by adambadura** [comment]
@flaudanum I think you can download the [`reStructuredText.xml`](https://github.com/steenhulthin/reStructuredText_NPP/blob/master/reStructuredText.xml) from here directly. Just go with the [raw](https://github.com/steenhulthin/reStructuredText_NPP/raw/master/reStructuredText.xml) button.

**Comment by steenhulthin** [comment]
Which theme do you prefer?
I think this issue has to be solved with a specific reStructuredText.xml file for dark themes.
(Sorry for my very late answer. I have been away open source project for quite some time.)

**Comment by flaudanum** [comment]
Hi @steenhulthin ,
The dark theme that I'm using is [Darkula](https://github.com/dracula/notepad-plus-plus).
Thanks again for this plugin.

**Comment by steenhulthin** [comment]
Basic support for dracula theme is now added. 7a8fc9023163a8afcc12076db1938b87e8a52a52
It will be included in next release. For now it can be downloaded here: https://raw.githubusercontent.com/steenhulthin/reStructuredText_NPP/master/reStructuredText_dracula.xml

**Comment by flaudanum** [comment]
Great job. Thank you! *Darcula* is a quite popular dark theme. I think it was worth the time.
Just so you know the background color of numbers is still white. To me it's OK but if you intend to correct it it's better you know it before the next release.
Thanks again.

**Comment by steenhulthin** [comment]
Thanks for letting me know. I'll look at it for next release. ;)
