### ISSUE TITLE
Download-link no longer working

### ISSUE THREAD

**Issue by Gabbalo** [steenhulthin/reStructuredText_NPP#4]
Hey there,

the provided downloadlink is no longer working due to a suspension of the corresponding hosting account.
Can you please include the needed file in this repository or bring the site back online?

**Comment by adambadura** [comment]
@Gabbalo I think you can download the [`reStructuredText.xml`](https://github.com/steenhulthin/reStructuredText_NPP/blob/master/reStructuredText.xml) from here directly. Just go with the [raw](https://github.com/steenhulthin/reStructuredText_NPP/raw/master/reStructuredText.xml) button.

**Comment by flaudanum** [comment]
Hi @adambadura ,
I'm the guy from the other issue [Non-white backgrounds](https://github.com/steenhulthin/reStructuredText_NPP/issues/3) but I think your answer will solve this one raised by @Gabbalo ;)

**Comment by adambadura** [comment]
@flaudanum sorry for disturbing you. I started to write the comment under your issue and even placed it but then quickly realized this was the wrong issue and I have moved the comment here, forgetting to update the mention. Now I did that also editing the comment above.

**Comment by flaudanum** [comment]
That's OK don't worry. Thanks for the pluggin by the way.

Le mer. 21 août 2019 à 12:44, Adam Badura <notifications@github.com> a
écrit :

**Comment by steenhulthin** [comment]
I have been away for open source projects for quite some time. Thank you for opening this issue. The download link should now work correctly again.
